export type TeamMember = {
  id: number;
  name: string;
  role: string;
  team: string;
  department?: string;
  branchYear?: string;
  image?: string;
  bio: string;
  linkedin?: string;
  github?: string;
  mail?: string;
  publishPhoto?: boolean;
  isLead?: boolean;
  year?: "2025-2026" | "2024-2025";
};

export type Teams = {
  [key: string]: TeamMember[];
};

// Faculty Advisors
export const facultyAdvisors: TeamMember[] = [
  {
    id: 101,
    name: "Dr. Deepika Ajalkar",
    role: "Head of Department",
    department: "Computer Science & Data Science",
    team: "Faculty Advisors",
    branchYear: "Faculty / HOD",
    image: "/img/team/deepika-ajalkar.png",
    bio: "Dedicated to guiding students toward academic excellence, pioneering computing research breakthroughs, and building world-class engineering foundations.",
    linkedin: "https://www.linkedin.com/school/ghrcem/",
    publishPhoto: true,
  },
  {
    id: 102,
    name: "Prof. Masira Kulkarni",
    role: "Faculty Coordinator",
    department: "ACM Student Chapter",
    team: "Faculty Advisors",
    branchYear: "Faculty Mentor",
    image: "/img/team/masira-kulkarni.png",
    bio: "Mentors emerging engineers with a focus on technical ingenuity, collaborative teamwork, student leadership, and community-driven initiatives.",
    linkedin: "https://www.linkedin.com/school/ghrcem/",
    publishPhoto: true,
  },
];

// Current Academic Year Team (2025–2026)
export const currentTeamMembers: TeamMember[] = [
  {
    id: 1,
    name: "Aditya Singh",
    role: "President",
    team: "Core",
    department: "Executive Board",
    branchYear: "B.Tech DS, 3rd year",
    image: "",
    bio: "Specializes in Data Engineering, C++, SQL, and Python, focusing on architecting scalable data pipelines and high-impact technology solutions.",
    linkedin: "https://www.linkedin.com/in/kumar-aditya-singh-5ba884373",
    github: "https://github.com/kumar-aditya79",
    mail: "kumar.singh.ds@ghrcemp.raisoni.net",
    publishPhoto: true,
    isLead: true,
    year: "2025-2026",
  },
  {
    id: 2,
    name: "Ishika Kestwal",
    role: "Vice President",
    team: "Core",
    department: "Executive Board",
    branchYear: "B.Tech CSE Cyber Security, 3rd year",
    image: "",
    bio: "Skilled in Python, networking fundamentals, and cybersecurity tooling, passionate about collaborative problem-solving and delivering practical software solutions.",
    linkedin: "https://www.linkedin.com/in/ishika-k-926b322b0/",
    github: "https://github.com/ishikakestwal",
    mail: "ishikakestwal27@gmail.com",
    publishPhoto: true,
    isLead: true,
    year: "2025-2026",
  },
  {
    id: 3,
    name: "Aman Kumar",
    role: "Secretary",
    team: "Core",
    department: "Executive Board",
    branchYear: "B.Tech Data Science, 3rd Year",
    image: "",
    bio: "Drives strategic operational planning, organized scheduling, transparent communications, and cross-team coordination to accelerate chapter milestones.",
    linkedin: "https://www.linkedin.com/in/aman-kumar-6307a7352",
    mail: "amankumar180806@gmail.com",
    publishPhoto: true,
    isLead: true,
    year: "2025-2026",
  },
  {
    id: 4,
    name: "Shifa Memon",
    role: "Treasurer",
    team: "Core",
    department: "Executive Board / Finance",
    branchYear: "B.Tech CSE Data Science, 3rd year",
    image: "",
    bio: "Combines data science fundamentals with fiscal administration and public speaking, enthusiastic about continuous learning and transparent governance.",
    linkedin: "https://www.linkedin.com/in/shifa-memon-220b90328",
    github: "https://github.com/sanikabavaskar",
    mail: "sharmin.shifu.74432@gmail.com",
    publishPhoto: true,
    isLead: true,
    year: "2025-2026",
  },
  {
    id: 5,
    name: "Saurabh Tomke",
    role: "Technical Lead",
    team: "Tech",
    department: "Technology & Development",
    branchYear: "B.Tech Cyber Security, 3rd year",
    image: "",
    bio: "Passionate about full-stack engineering, cloud architecture, cybersecurity defense, and fostering an open developer ecosystem through hands-on workshops.",
    linkedin: "https://www.linkedin.com/in/saurabh-tomke/",
    github: "https://github.com/Saurabh0003M",
    mail: "saurabh.tomke@gmail.com",
    publishPhoto: true,
    isLead: true,
    year: "2025-2026",
  },
  {
    id: 6,
    name: "Sanika Bavaskar",
    role: "Design Lead",
    team: "Design",
    department: "UI/UX & Creative Design",
    branchYear: "B.Tech CSE Data Science, 3rd year",
    image: "",
    bio: "Blends coding logic and visual design to craft seamless digital experiences, exploring generative AI, interactive typography, and modern user interfaces.",
    linkedin: "https://www.linkedin.com/in/sanika-bavaskar-473810325",
    github: "https://github.com/sanikabavaskar",
    mail: "sanika222kar@gmail.com",
    publishPhoto: false,
    isLead: true,
    year: "2025-2026",
  },
  {
    id: 7,
    name: "Vedant Thorat",
    role: "Tech Member",
    team: "Tech",
    department: "Technology & Development",
    branchYear: "B.Tech CSE Cyber Security, 2nd Year",
    image: "",
    bio: "Enthusiastic modern software developer exploring AI-assisted coding workflows, full-stack applications, and interactive web technologies.",
    linkedin: "https://www.linkedin.com/in/vedant-thorat-b6b036369",
    github: "https://github.com/CHV09",
    mail: "vedant.thorat.csecyb@ghrcemp.raisoni.net",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 8,
    name: "Tanmay Bulbule",
    role: "Tech Member",
    team: "Tech",
    department: "Technology & Development",
    branchYear: "B.Tech COE, 2nd year",
    image: "",
    bio: "Explores Generative AI, Python scripting, and system automation while actively designing and shipping practical AI-driven utilities.",
    linkedin: "https://www.linkedin.com/in/tanmaybulbule/",
    github: "https://github.com/Bulbule-Tanmay",
    mail: "bulbuletanmay08@gmail.com",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 9,
    name: "Ram Polawar",
    role: "Core Member",
    team: "Tech",
    department: "Tech & Entrepreneurship",
    branchYear: "B.Tech, 2nd year",
    image: "",
    bio: "Founder & CEO of Business360. Passionate about entrepreneurship, applied AI, and building intelligent automation systems that help businesses scale.",
    linkedin: "https://www.linkedin.com/in/ram-polawar-3a587a316",
    github: "https://github.com/rampolawar402-max",
    mail: "rampolawar402@gmail.com",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 10,
    name: "Sameer Karanache",
    role: "Design Member",
    team: "Design",
    department: "UI/UX & Graphics",
    branchYear: "B.Tech IT, 2nd year",
    image: "",
    bio: "Graphic designer with Unity Engine expertise and an entrepreneurial drive, translating creative concepts into bold and impactful visual branding.",
    linkedin: "https://www.linkedin.com/in/sameer-karanache-0b1386410",
    mail: "sameer.karanache.it@ghrcemp.raisoni.net",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 11,
    name: "Shivbhakti Malipatil",
    role: "PR & Events Member",
    team: "Public Relations & Event Management",
    department: "PR & Event Management",
    branchYear: "B.Tech DS, 2nd year",
    image: "",
    bio: "Proficient in C++ and Python development, with a growing focus on technical problem-solving, active student outreach, and event coordination.",
    linkedin: "https://www.linkedin.com/in/shivbhakti-malipatil-a129a2385",
    mail: "shivbhaktimalipatil19@gmail.com",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 12,
    name: "Chaitanya Kumar",
    role: "Event Management Member",
    team: "Public Relations & Event Management",
    department: "PR & Event Management",
    branchYear: "B.Tech Data Science, 2nd year",
    image: "",
    bio: "Brings strong interpersonal communication, agile coordination, and problem-solving skills to manage logistics and create memorable tech gatherings.",
    linkedin: "https://www.linkedin.com/in/chaitanya-amit-kumar-4b1a15422",
    mail: "ck200784@gmail.com",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 13,
    name: "Shivanjali Chavan",
    role: "PR & Events Member",
    team: "Public Relations & Event Management",
    department: "PR & Event Management",
    branchYear: "B.Tech COE, 2nd yr",
    image: "",
    bio: "Contributes creative ideas, positive team dynamics, and efficient workflow execution to deliver engaging chapter hackathons and seminars.",
    linkedin: "https://www.linkedin.com/in/shivanjali-chavan-0087b9385",
    mail: "shivanjali.chavan.cre@ghrcemp.raisoni.net",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 14,
    name: "Shreya Dorkade",
    role: "PR & Events Member",
    team: "Public Relations & Event Management",
    department: "PR & Event Management",
    branchYear: "B.Tech CSE Data Science, 2nd year",
    image: "",
    bio: "Dedicated to building interpersonal and technical expertise, coordinating student outreach programs, and fostering an inclusive tech community.",
    linkedin: "https://www.linkedin.com/in/shreya-dorkade-262086428",
    mail: "shreya17dorkade@gmail.com",
    publishPhoto: false,
    year: "2025-2026",
  },
  {
    id: 15,
    name: "Ankita Ahir",
    role: "PR & Events Member",
    team: "Public Relations & Event Management",
    department: "PR & Event Management",
    branchYear: "B.Tech CSE Data Science, 2nd year",
    image: "",
    bio: "Enjoys bringing community tech events to life while actively expanding domain skills in data science, analytics, and software development.",
    linkedin: "https://www.linkedin.com/in/ankita-ahir-190016428",
    mail: "ankita.ahir.cseds@ghrcemp.raisoni.net",
    publishPhoto: false,
    year: "2025-2026",
  },
  {
    id: 16,
    name: "Laxmi Patil",
    role: "Documentation Member",
    team: "Documentation",
    department: "Documentation & Content",
    branchYear: "B.Tech ENTC, 2nd year",
    image: "",
    bio: "Crafts structured technical documentation, archival proceedings, and clear communications that ensure seamless institutional memory.",
    linkedin: "https://www.linkedin.com/in/laxmi-patil-9742913a1",
    github: "https://github.com/laxmipatil2124",
    mail: "laxmipatil5106@gmail.com",
    publishPhoto: true,
    year: "2025-2026",
  },
  {
    id: 17,
    name: "Sheema Shaikh",
    role: "Documentation Member",
    team: "Documentation",
    department: "Documentation & Content",
    branchYear: "B.Tech DS, 2nd year",
    image: "",
    bio: "Maintains meticulous records of chapter sessions, workshop agendas, and technical activities with an eye for precision and clarity.",
    linkedin: "https://www.linkedin.com/in/sheema-shaikh-83a814395",
    mail: "sheemashaikh2006@gmail.com",
    publishPhoto: false,
    year: "2025-2026",
  },
];

// Previous Year Leads (2024–2025)
export const previousYearLeads: TeamMember[] = [
  {
    id: 201,
    name: "Aditya Kurhade",
    role: "Former President",
    team: "Previous Leads",
    department: "Executive Board (2024-25)",
    branchYear: "Alumni / Senior Lead",
    image: "/img/team/aditya-kurhade.png",
    bio: "Spearheaded the chapter's establishment, championed competitive programming, and set high benchmarks for student leadership.",
    linkedin: "https://www.linkedin.com/in/aditya-kurhade",
    publishPhoto: true,
    isLead: true,
    year: "2024-2025",
  },
  {
    id: 202,
    name: "Shubham Sahu",
    role: "Former Vice President",
    team: "Previous Leads",
    department: "Executive Board & Tech (2024-25)",
    branchYear: "Alumni / Senior Lead",
    image: "/img/team/shubham-sahu.png",
    bio: "Architected backend infrastructure, orchestrated institute hackathons, and nurtured developer communities across engineering disciplines.",
    linkedin: "https://www.linkedin.com/in/shubham-sahu-2548b4291",
    github: "https://github.com/02-Shubham",
    publishPhoto: true,
    isLead: true,
    year: "2024-2025",
  },
  {
    id: 203,
    name: "Krishna Gavali",
    role: "Former Technical Lead",
    team: "Previous Leads",
    department: "Technology & Engineering (2024-25)",
    branchYear: "Alumni / Senior Lead",
    image: "/img/team/krishna-gavali.png",
    bio: "Directed core engineering initiatives, hands-on developer workshops, and code mentorship tracks that accelerated student skillsets.",
    linkedin: "https://www.linkedin.com/",
    publishPhoto: true,
    isLead: true,
    year: "2024-2025",
  },
  {
    id: 204,
    name: "Mansi Patil",
    role: "Former PR Lead",
    team: "Previous Leads",
    department: "Public Relations (2024-25)",
    branchYear: "Alumni / Senior Lead",
    image: "/img/team/mansi-patil.png",
    bio: "Expanded inter-college partnerships, amplified digital outreach, and significantly increased student chapter visibility across the region.",
    linkedin: "https://www.linkedin.com/",
    publishPhoto: true,
    isLead: true,
    year: "2024-2025",
  },
  {
    id: 205,
    name: "Anurag Jadhav",
    role: "Former Event Management Lead",
    team: "Previous Leads",
    department: "Events & Operations (2024-25)",
    branchYear: "Alumni / Senior Lead",
    image: "/img/team/anurag-jadhav.jpg",
    bio: "Managed large-scale college technical symposiums, hackathons, and industry speaker tracks with seamless operational precision.",
    linkedin: "https://www.linkedin.com/in/anurag-jadhav-4287a5281",
    publishPhoto: true,
    isLead: true,
    year: "2024-2025",
  },
  {
    id: 206,
    name: "Shubham Singh",
    role: "Former Design Lead",
    team: "Previous Leads",
    department: "Creative & Branding (2024-25)",
    branchYear: "Alumni / Senior Lead",
    image: "/img/team/shubham-singh.jpg",
    bio: "Created the chapter's foundational brand identity, promotional media assets, and digital design language across all platforms.",
    linkedin: "https://www.linkedin.com/in/shubham-singh-034263286",
    publishPhoto: true,
    isLead: true,
    year: "2024-2025",
  },
  {
    id: 207,
    name: "Vaishnavi Gaikwad",
    role: "Former Treasurer Lead",
    team: "Previous Leads",
    department: "Treasury & Finance (2024-25)",
    branchYear: "Alumni / Senior Lead",
    image: "/img/team/vaishnavi-gaikwad.jpg",
    bio: "Oversaw chapter sponsorships, financial accounting, budget allocations, and transparent fiscal governance for all events.",
    linkedin: "https://www.linkedin.com/in/vaishnavi-gaikwad",
    publishPhoto: true,
    isLead: true,
    year: "2024-2025",
  },
];

// Organized Teams Object by Category
export const teams: Teams = {
  "Faculty Advisors": facultyAdvisors,
  "Core Leads": currentTeamMembers.filter((m) => m.team === "Core" || m.isLead),
  "Tech": currentTeamMembers.filter((m) => m.team === "Tech" || m.role.includes("Tech") || m.role.includes("President")),
  "Design": currentTeamMembers.filter((m) => m.team === "Design"),
  "Public Relations & Event Management": currentTeamMembers.filter((m) => m.team === "Public Relations & Event Management"),
  "Documentation": currentTeamMembers.filter((m) => m.team === "Documentation"),
  "Finance & Treasury": currentTeamMembers.filter((m) => m.role.includes("Treasurer")),
  "Previous Year Leads": previousYearLeads,
};
